version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: Practitioner
    env_file:
      - .env
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo:
